Repository prgrms-fe-devcourse/FEDC5_jackpot_letter_Donguk, pull requests merged in 2023-12, with the labels that each got.

#2 프로젝트 초기 세팅
  .eslintrc.cjs
  .gitignore
  .prettierrc
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙️ setting

#9 ✨ feat: toast 추가
  package-lock.json
  package.json
  src/App.tsx
Labels: ✨feat

#11 ✨feat: LocalStorage utils 구현
  .gitignore
  src/utils/LocalStorage/index.ts
Labels: ✨feat, 🛠️refactor

#13 🔧setting: vercel CLI 추가 및 vercel 개발환경 script 실행문 추가
  .gitignore
  package-lock.json
  package.json
Labels: ⚙️ setting

#15 ✨ feat: 공통 컴포넌트 Input 구현
  src/components/Common/Input/index.style.tsx
  src/components/Common/Input/index.tsx
Labels: ✨feat

#18 🔨 refactor: typescript index signature 구현
  src/components/Common/Input/index.tsx
Labels: 🛠️refactor

#24 💄 design: emotion theme 적용
  src/App.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
Labels: 💄 design

#14 ✨feat: 공통 컴포넌트 모달 구현
  src/App.tsx
  src/components/Common/Modal/index.style.tsx
  src/components/Common/Modal/index.tsx
  src/hooks/useModal.tsx
  src/index.css
  src/main.tsx
  src/styles/reset.tsx
Labels: ✨feat, 코드리뷰요청

#25 ✨feat: 공통 컴포넌트 button 구현
  src/App.tsx
  src/components/Common/Button/index.style.tsx
  src/components/Common/Button/index.tsx
  src/components/Common/Button/type.tsx
Labels: ✨feat

#30 💄 design: Input 컴포넌트 style props 추가, App.tsx 코드 정리
  src/App.css
  src/App.tsx
  src/components/Common/Input/index.style.tsx
  src/components/Common/Input/index.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
Labels: 🛠️refactor, 💄 design

#33 design: button border 수정
  src/components/Common/Button/index.style.tsx
Labels: 💄 design

#29 🔧setting: husky 및 import rule 설정
  .eslintcache
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  tsconfig.json
Labels: ⚙️ setting
