Repository prgrms-fe-devcourse/FEDC5_jackpot_letter_Donguk, pull requests merged in 2024-01, with the labels that each got.

#35 🔧setting: font 적용 및 스토리북 적용
  .eslintrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  public/assets/fonts/Pretendard-Bold.woff2
  public/assets/fonts/Pretendard-Medium.woff2
  public/assets/fonts/Pretendard-Regular.woff2
  public/assets/fonts/fonts.d.ts
  src/App.tsx
  src/components/Common/Modal/index.stories.tsx
  src/components/Common/Modal/index.tsx
  src/hooks/useModal.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/global.tsx
Labels: ⚙️ setting, 💄 design, 코드리뷰요청

#47 ✨ feat: 채널 페이지 UI 구현
  .eslintcache
  .gitignore
  package.json
  src/assets/channel.svg
  src/assets/channelWithLine.svg
  src/components/ChannelList/ChannelIcon/index.style.tsx
  src/components/ChannelList/ChannelIcon/index.tsx
  src/pages/ChannelList/index.style.tsx
  src/pages/ChannelList/index.tsx
  src/styles/global.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
Labels: ✨feat, 💄 design

#40 ✨TanStack, ApI 함수 구현
  api/index.ts
  public/assets/fonts/fonts.d.ts
  src/App.tsx
  src/api/auth.ts
  src/api/channel.ts
  src/hooks/api/useGetChannelList.ts
  src/pages/ChannelList/index.tsx
Labels: ✨feat, 코드리뷰요청

#38 💄 design: 반응형 설정 추가
  src/App.tsx
  src/styles/_reset.tsx
  src/styles/_responsive.tsx
  src/styles/index.tsx
Labels: ⚙️ setting, 💄 design

#41 ✨ feat: mypage UI 구현
  .husky/pre-commit
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/empty_user.png
  src/components/Common/Button/index.style.tsx
  src/components/Mypage/Comments/index.style.tsx
  src/components/Mypage/Comments/index.tsx
  src/components/Mypage/Follow/index.style.tsx
  src/components/Mypage/Follow/index.tsx
  src/components/Mypage/FollowList/index.style.tsx
  src/components/Mypage/FollowList/index.tsx
  src/components/Mypage/PasswordUpdate/index.style.tsx
  src/components/Mypage/PasswordUpdate/index.tsx
  src/components/Mypage/PostList/index.tsx
  src/components/Mypage/PostList/indext.style.tsx
  src/components/Mypage/ProfileImg/index.style.tsx
  src/components/Mypage/ProfileImg/index.tsx
  src/components/Mypage/ProfileUpdate/index.style.tsx
  src/components/Mypage/ProfileUpdate/index.tsx
  src/components/Mypage/Sidebar/index.style.tsx
  src/components/Mypage/Sidebar/index.tsx
  src/components/Mypage/SidebarItem/index.style.tsx
  src/components/Mypage/SidebarItem/index.tsx
  src/pages/CommentListPage/index.tsx
  src/pages/FollowPage/index.tsx
  src/pages/LikeListPage/index.tsx
  src/pages/Mypage/index.style.tsx
  src/pages/Mypage/index.tsx
  src/pages/PostListPage/index.tsx
  src/styles/_reset.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
Labels: ✨feat, 💄 design, 코드리뷰요청

#43 ✨ feat: 로그인, 회원가입 UI 구현
  package-lock.json
  package.json
  src/assets/images/LongLogo.svg
  src/assets/images/ShortLogo.svg
  src/components/Account/Description/index.style.tsx
  src/components/Account/Description/index.tsx
  src/components/Account/SignInForm/index.tsx
  src/components/Account/SingUpForm/index.style.tsx
  src/components/Account/SingUpForm/index.tsx
  src/components/Account/index.style.tsx
  src/components/Account/index.tsx
  src/constants/account.ts
  src/constants/regex.ts
  src/utils/validation.ts
Labels: ✨feat, 💄 design

#50 ✨ feat: channel page UI 구현
  src/assets/OpenChannel.svg
  src/assets/Pointer.svg
  src/assets/TransparentChannel.svg
  src/assets/channelWithLine.svg
  src/assets/channelWithLongLine.svg
  src/components/Channel/ChannelAnimation/index.style.tsx
  src/components/Channel/ChannelAnimation/index.tsx
  src/components/Channel/ChannelClose/index.style.tsx
  src/components/Channel/ChannelClose/index.tsx
  src/components/Channel/ChannelOpen/index.style.tsx
  src/components/Channel/ChannelOpen/index.tsx
  src/components/Common/Button/index.tsx
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.tsx
Labels: ✨feat

#55 ✨feat: 포스트/댓글 페이지 구현
  .env
  .eslintcache
  .gitignore
  src/assets/Like.svg
  src/assets/ShortLogo.svg
  src/assets/WarningLogo.svg
  src/components/Post/Footer/index.style.tsx
  src/components/Post/Footer/index.tsx
  src/components/Post/Header/index.style.tsx
  src/components/Post/Header/index.tsx
  src/components/Post/Letter/index.style.tsx
  src/components/Post/Letter/index.tsx
  src/components/Post/Warning/index.style.tsx
  src/components/Post/Warning/index.tsx
  src/components/Post/index.style.tsx
  src/components/Post/index.tsx
  src/components/PostComment/Comment/index.style.tsx
  src/components/PostComment/Comment/index.tsx
  src/components/PostComment/Footer/index.style.tsx
  src/components/PostComment/Footer/index.tsx
  src/components/PostComment/Header/index.style.tsx
  src/components/PostComment/Header/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.style.tsx
  src/components/PostComment/index.tsx
  src/main.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
Labels: ✨feat

#56 ✨ feat : channel 생성 페이지 구현
  src/assets/Private.svg
  src/assets/Public.svg
  src/assets/background/background0.png
  src/assets/background/background1.png
  src/assets/background/background2.png
  src/assets/background/background3.png
  src/assets/background/background4.png
  src/assets/background/background5.png
  src/assets/background/background6.png
  src/assets/background/background7.png
  src/assets/background/background8.png
  src/components/ChannelTemplate/AccessCandidate/index.style.tsx
  src/components/ChannelTemplate/AccessCandidate/index.tsx
  src/components/ChannelTemplate/SelectAccess/index.style.tsx
  src/components/ChannelTemplate/SelectAccess/index.tsx
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/components/ChannelTemplate/SelectBackground/index.tsx
  src/components/ChannelTemplate/SelectColor/index.style.tsx
  src/components/ChannelTemplate/SelectColor/index.tsx
  src/components/ChannelTemplate/SelectColor/type.ts
  src/components/Common/CustomChannelIcon/index.tsx
  src/pages/ChannelTemplate/index.style.tsx
  src/pages/ChannelTemplate/index.tsx
Labels: ✨feat

#61 🔨 refactor: import 경로 수정
  src/hooks/api/useConfirmAuthQuery.ts
  src/hooks/api/useSignInMutation.ts
  src/hooks/api/useSignUpMutation.ts
Labels: 🛠️refactor

#63 🔨refactor: post, comment 페이지 style 관련 라우팅 경로 수정 및 ThemeProvider, Global 컴포넌트 위치 변경 App.tsx -> Main.tsx
  package-lock.json
  src/components/Post/index.tsx
  src/components/PostComment/index.tsx
  src/main.tsx
Labels: 🛠️refactor

#65 🔨refactor: App.tsx 라우팅 수정
  src/App.tsx
  src/main.tsx
Labels: 🛠️refactor

#70 ✨ feat: 로그인, 회원가입 API 연동
  src/components/Account/SignInForm/index.tsx
  src/components/Account/SignUpForm/index.style.tsx
  src/components/Account/SignUpForm/index.tsx
  src/components/Account/index.style.tsx
  src/components/Account/index.tsx
  src/components/Common/Input/index.tsx
  src/constants/api.ts
  src/hooks/api/useSignUpMutation.ts
Labels: ✨feat, 💄 design

#69 🔨 refactor: 권한별 페이지 라우팅 수정
  src/App.tsx
  src/constants/path.ts
  src/main.tsx
  src/pages/SignUpPage/index.tsx
  src/route/AppRouter.tsx
  src/route/AuthMiddleware.tsx
Labels: 🛠️refactor

#72 ✨ feat: 채널 관련 페이지 API 연동
  api/index.ts
  src/api/channel.ts
  src/assets/channel.svg
  src/components/Channel/ChannelOpen/index.tsx
  src/components/ChannelList/ChannelIcon/index.tsx
  src/components/ChannelTemplate/SelectAccess/index.style.tsx
  src/components/ChannelTemplate/SelectAccess/index.tsx
  src/components/ChannelTemplate/SelectBackground/index.tsx
  src/components/ChannelTemplate/SelectColor/index.tsx
  src/components/Mypage/ProfileUpdate/index.tsx
  src/components/Post/Header/index.tsx
  src/components/Post/Warning/index.tsx
  src/components/PostComment/Header/index.tsx
  src/components/PostComment/PrePost/index.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/useChannelListQuery.ts
  src/hooks/api/useChannelQuery.ts
  src/hooks/api/useNewChannel.ts
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.tsx
  src/pages/ChannelTemplate/index.tsx
  src/route/AppRouter.tsx
  src/store/auth.ts
  src/styles/_reset.tsx
Labels: ✨feat

#77 ✨ feat: 채널 옵션 적용
  src/assets/OpenChannel.svg
  src/assets/TransparentChannel.svg
  src/assets/background/background4.png
  src/assets/background/gradation.png
  src/assets/background/mountain.png
  src/assets/background/mountain2.png
  src/assets/background/mountain3.png
  src/assets/background/original.png
  src/assets/background/paper.png
  src/assets/background/paper2.png
  src/assets/background/per.png
  src/assets/background/see.png
  src/assets/channelWithLine.svg
  src/components/Channel/ChannelAnimation/index.style.tsx
  src/components/Channel/ChannelClose/index.style.tsx
  src/components/Channel/ChannelClose/index.tsx
  src/components/Channel/ChannelOpen/index.style.tsx
  src/components/Channel/ChannelOpen/index.tsx
  src/components/ChannelList/ChannelIcon/index.tsx
  src/components/ChannelTemplate/SelectAccess/index.tsx
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/components/ChannelTemplate/SelectBackground/index.tsx
  src/components/ChannelTemplate/SelectBackground/type.ts
  src/components/ChannelTemplate/SelectColor/index.tsx
  src/components/ChannelTemplate/SelectColor/type.ts
  src/components/Common/CustomChannelIcon/OpenChannel.tsx
  src/components/Common/CustomChannelIcon/index.tsx
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.style.tsx
  src/pages/ChannelTemplate/index.tsx
  src/types/channel.ts
  src/utils/parse.ts
Labels: ✨feat, 💄 design

#78 ✨feat: 마이페이지 api연동
  api/index.ts
  src/App.tsx
  src/api/follow.ts
  src/api/post.ts
  src/api/user.ts
  src/components/ChannelTemplate/SelectColor/index.tsx
  src/components/Mypage/Follow/index.tsx
  src/components/Mypage/FollowList/index.style.tsx
  src/components/Mypage/FollowList/index.tsx
  src/components/Mypage/FollowListItem/index.style.tsx
  src/components/Mypage/FollowListItem/index.tsx
  src/components/Mypage/PasswordUpdate/index.tsx
  src/components/Mypage/PostList/index.tsx
  src/components/Mypage/ProfileUpdate/index.style.tsx
  src/components/Mypage/ProfileUpdate/index.tsx
  src/components/Mypage/Sidebar/index.style.tsx
  src/components/Post/Header/index.tsx
  src/components/Post/Letter/index.tsx
  src/components/Post/Warning/index.tsx
  src/components/PostComment/Header/index.tsx
  src/components/PostComment/PrePost/index.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/useAuthorPost.ts
  src/hooks/api/useCreateFollow.ts
  src/hooks/api/useDeleteFollow.ts
  src/hooks/api/useUpdatePassword.ts
  src/hooks/api/useUpdateUser.ts
  src/hooks/api/useUser.ts
  src/hooks/api/useUserFollowList.ts
  src/hooks/api/useUserLikeList.ts
  src/main.tsx
  src/pages/ChannelList/index.tsx
  src/pages/FollowPage/index.tsx
  src/pages/LikeListPage/index.tsx
  src/pages/Mypage/index.style.tsx
  src/pages/Mypage/index.tsx
  src/pages/PostListPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/route/AuthMiddleware.tsx
  src/store/user.ts
  src/styles/global.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
  src/types/ResponseType.tsx
Labels: ✨feat, 코드리뷰요청

#80 🔨 fix: 채널 오류 수정
  package-lock.json
  src/api/channel.ts
  src/components/ChannelTemplate/SelectColor/index.tsx
  src/components/Common/CustomChannelIcon/index.tsx
  src/hooks/api/useNewChannel.ts
  src/pages/ChannelTemplate/index.tsx
Labels: 🐛 fix

#83 ✨Feat/#82/post like
  api/index.ts
  src/api/like.ts
  src/api/member.ts
  src/api/post.ts
  src/assets/complete.svg
  src/assets/delete.svg
  src/assets/edit.svg
  src/assets/loading.svg
  src/components/Channel/ChannelOpen/index.tsx
  src/components/Post/Letter/index.tsx
  src/components/Post/index.tsx
  src/components/PostComment/Comment/index.style.tsx
  src/components/PostComment/Comment/index.tsx
  src/components/PostComment/Loading/index.style.tsx
  src/components/PostComment/Loading/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.tsx
  src/constants/api.ts
  src/hooks/api/useLikeCreateMutation.ts
  src/hooks/api/useLikeDeleteMutation.ts
  src/hooks/api/usePostCommentCreateMutation.ts
  src/hooks/api/usePostCreateMutation.ts
  src/hooks/api/usePostDeleteMutation.ts
  src/hooks/api/usePostUpdateMutation.ts
  src/hooks/api/useUserInfomationQuery.ts
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.tsx
  src/route/AppRouter.tsx
Labels: ✨feat

#84 ✨ feat: 주머니 선택 페이지 구현
  src/assets/letter/blue.png
  src/assets/letter/green.png
  src/assets/letter/mint.png
  src/assets/letter/orange.png
  src/assets/letter/pink.png
  src/assets/letter/purple.png
  src/assets/letter/red.png
  src/assets/letter/white.png
  src/assets/letter/yellow.png
  src/components/Channel/ChannelOpen/index.tsx
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/components/ChannelTemplate/SelectColor/index.tsx
  src/constants/path.ts
  src/hooks/api/useNewChannel.ts
  src/pages/PostCreate/index.tsx
  src/route/AppRouter.tsx
Labels: ✨feat

#86 ✨ feat: axios instance 구현
  src/api/HTTPError.ts
  src/api/axiosInstance.ts
  src/api/index.d.ts
  src/constants/api.ts
Labels: ✨feat

#87 🔨 refactor: 로그인, 회원가입 에러 해결, 리팩토링
  src/App.tsx
  src/api/member.ts
  src/components/Account/FormInput/index.tsx
  src/components/Account/SignInForm/SignInBtn/index.tsx
  src/components/Account/SignInForm/index.tsx
  src/components/Account/SignUpForm/InputName/index.style.tsx
  src/components/Account/SignUpForm/InputName/index.tsx
  src/components/Account/SignUpForm/index.style.tsx
  src/components/Account/SignUpForm/index.tsx
  src/components/Common/Button/index.tsx
  src/constants/account.ts
  src/constants/api.ts
  src/constants/regex.ts
  src/hooks/api/useSignInMutation.ts
  src/hooks/api/useSignUpMutation.ts
  src/utils/validation.ts
Labels: 🛠️refactor, 💄 design

#91 ✨ feat: 다크 모드 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Account/index.style.tsx
  src/components/Account/index.tsx
  src/components/Common/DarkMode/index.tsx
  src/components/Common/Logo/LongLogo.tsx
  src/components/Common/Logo/ShortLogo.tsx
  src/constants/api.ts
  src/hooks/useTheme.tsx
  src/main.tsx
  src/store/theme.ts
  src/styles/_reset.tsx
  src/styles/global.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
Labels: ✨feat

#95 ✨ feat: 404 에러 페이지 구현
  src/App.tsx
  src/assets/Animation - 1704792254812.json
  src/assets/Animation - 1704792709727.json
  src/pages/NotFoundPage/index.style.tsx
  src/pages/NotFoundPage/index.tsx
Labels: ✨feat

#96 ✨feat: 댓글 페이지 이전 댓글 삭제 기능 구현
  src/components/Channel/ChannelOpen/index.tsx
  src/components/Post/Header/index.tsx
  src/components/Post/Warning/index.tsx
  src/components/PostComment/Header/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.tsx
  src/hooks/api/useCommentDeleteMutation.ts
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.tsx
  src/pages/PostCreate/index.tsx
  src/route/AppRouter.tsx
Labels: ✨feat, 🛠️refactor

#97 ✨feat: 마이페이지 추가 페이지 작업
  .eslintcache
  api/index.ts
  src/App.tsx
  src/api/post.ts
  src/api/user.ts
  src/components/ChannelTemplate/SelectColor/index.tsx
  src/components/Common/Button/index.tsx
  src/components/Common/Logo/LongLogo.tsx
  src/components/Common/Logo/ShortLogo.tsx
  src/components/Common/ProfileImg/index.style.tsx
  src/components/Common/ProfileImg/index.tsx
  src/components/Mypage/Comments/index.style.tsx
  src/components/Mypage/Comments/index.tsx
  src/components/Mypage/Empty/index.style.tsx
  src/components/Mypage/Empty/index.tsx
  src/components/Mypage/FollowListItem/index.tsx
  src/components/Mypage/Header/index.style.tsx
  src/components/Mypage/Header/index.tsx
  src/components/Mypage/PasswordUpdate/index.tsx
  src/components/Mypage/PostList/index.tsx
  src/components/Mypage/PostList/indext.style.tsx
  src/components/Mypage/ProfileUpdate/index.style.tsx
  src/components/Mypage/ProfileUpdate/index.tsx
  src/components/Mypage/Sidebar/index.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/constants/sidebar.ts
  src/hooks/api/useAuthorPost.ts
  src/hooks/api/useChannelPost.ts
  src/hooks/api/useCreateUserPhoto.ts
  src/hooks/api/useUpdateUser.ts
  src/hooks/api/useUserComment.ts
  src/hooks/api/useUserLikeList.ts
  src/pages/Channel/index.tsx
  src/pages/CommentListPage/index.tsx
  src/pages/Mypage/index.style.tsx
  src/pages/Mypage/index.tsx
  src/pages/PostListPage/index.tsx
  src/pages/ReceivedPostListPage/index.tsx
  src/route/AppRouter.tsx
  src/types/ResponseType.tsx
  src/utils/validation.ts
Labels: ✨feat

#101 ✨ Feat: Post 페이지 편지 작성 시 페이지 이동 및 성공 여부 Toast 노출
  package-lock.json
  package.json
  src/api/post.ts
  src/components/Post/index.tsx
  src/hooks/api/usePostCreateMutation.ts
  src/pages/Channel/index.tsx
  src/pages/PostCreate/index.tsx
Labels: ✨feat

#105 ✨feat: 알람 기능 구현
  .gitignore
  package-lock.json
  package.json
  src/api/user.ts
  src/assets/Alarm.svg
  src/assets/Comment.svg
  src/assets/Follow.svg
  src/assets/Message.svg
  src/assets/New.svg
  src/assets/Post.svg
  src/components/Alarm/AlarmItem/index.style.tsx
  src/components/Alarm/AlarmItem/index.tsx
  src/components/Alarm/AlarmItem/type.ts
  src/components/Alarm/AlarmList/index.style.tsx
  src/components/Alarm/AlarmList/index.tsx
  src/components/Common/Modal/index.stories.tsx
  src/components/Common/Modal/index.style.tsx
  src/components/Common/Modal/index.tsx
  src/constants/api.ts
  src/hooks/api/useNewNotification.ts
  src/hooks/api/useNotifycations.ts
  src/hooks/api/useUpdateNotification.ts
  src/hooks/useModal.tsx
  src/pages/Channel/index.tsx
  src/theme/emotion.d.ts
  src/theme/index.ts
  src/types/ResponseType.tsx
Labels: ✨feat

#106 ✨ feat: 검색 기능 구현
  src/api/channel.ts
  src/assets/Search.svg
  src/components/Common/SearchBar/index.style.tsx
  src/components/Common/SearchBar/index.tsx
  src/constants/api.ts
  src/hooks/api/useSearch.ts
  src/pages/ChannelList/index.style.tsx
  src/pages/ChannelList/index.tsx
Labels: ✨feat

#110 ✨Feat 메시지 리스트 페이지 구현
  src/api/user.ts
  src/assets/search.svg
  src/components/MessageList/Header/index.style.tsx
  src/components/MessageList/Header/index.tsx
  src/components/MessageList/SearchBar/index.style.tsx
  src/components/MessageList/SearchBar/index.tsx
  src/components/MessageList/UserList/index.style.tsx
  src/components/MessageList/UserList/index.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/useSignInMutation.ts
  src/hooks/api/useUserListDataQuery.ts
  src/pages/MessageListPage/index.tsx
  src/route/AppRouter.tsx
Labels: ✨feat

#113 💄 design: 채널관련 페이지 디자인 수정
  src/assets/background/gradation.png
  src/components/Channel/ChannelClose/index.style.tsx
  src/components/Channel/ChannelClose/index.tsx
  src/components/ChannelList/ChannelIcon/index.style.tsx
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/components/ChannelTemplate/SelectBackground/index.tsx
  src/components/Common/HamburgerMenu/index.tsx
  src/components/Common/Pagenation/index.style.tsx
  src/components/Common/Pagenation/index.tsx
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.style.tsx
  src/pages/PostCreate/index.tsx
  src/utils/parse.ts
Labels: 💄 design

#114 💄 design: 반응형 레이아웃 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Common/Logo/TitleLogo.tsx
  src/components/Common/Responsive/ResponsiveLayout/index.style.tsx
  src/components/Common/Responsive/ResponsiveLayout/index.tsx
  src/components/Common/Responsive/index.style.tsx
  src/components/Common/Responsive/index.tsx
  src/pages/Mypage/index.style.tsx
  src/pages/Mypage/index.tsx
  src/pages/NotFoundPage/index.style.tsx
  src/pages/NotFoundPage/index.tsx
  src/route/AppRouter.tsx
  src/styles/global.tsx
Labels: 💄 design

#124 🔨 refactor: 컴포넌트, 페이지 레이아웃 수정
  src/components/Account/Description/index.style.tsx
  src/components/Account/Description/index.tsx
  src/components/Account/FormInput/index.tsx
  src/components/Account/InputName/index.style.tsx
  src/components/Account/InputName/index.tsx
  src/components/Account/SignInBtn/index.tsx
  src/components/Account/SignInForm/index.tsx
  src/components/Account/SignUpForm/index.tsx
  src/components/Common/Button/index.style.tsx
  src/components/Common/Input/index.style.tsx
  src/components/Common/Input/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.style.tsx
  src/pages/SignUpPage/index.tsx
Labels: 🛠️refactor

#123 📎 chore: 오픈그래프, favicon, title 추가
  index.html
  public/favicon.ico
  public/thumbnail.jpg
Labels: 📎 chore

#121 🔨refactor: post, comment, messageList, message 관련 페이지 전반적인 리팩토링
  api/index.ts
  src/api/like.ts
  src/api/message.ts
  src/api/post.ts
  src/api/user.ts
  src/components/Channel/ChannelButton/index.tsx
  src/components/Channel/ChannelOpen/index.tsx
  src/components/Channel/ChannelPosts/index.tsx
  src/components/Common/HamburgerMenu/index.tsx
  src/components/Common/Modal/index.tsx
  src/components/Message/DM/index.style.tsx
  src/components/Message/DM/index.tsx
  src/components/Message/SendMessage/index.tsx
  src/components/MessageList/Header/index.tsx
  src/components/MessageList/UserList/index.style.tsx
  src/components/MessageList/UserList/index.tsx
  src/components/Post/Header/index.tsx
  src/components/Post/Warning/index.tsx
  src/components/Post/index.tsx
  src/components/PostComment/Comment/index.tsx
  src/components/PostComment/Header/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.tsx
  src/constants/api.ts
  src/hooks/api/useCommentDeleteMutation.ts
  src/hooks/api/useCreateNotification.ts
  src/hooks/api/useGetMessageConversations.ts.ts
  src/hooks/api/useGetMessagesQuery.ts
  src/hooks/api/useLikeCreateMutation.ts
  src/hooks/api/useLikeDeleteMutation.ts
  src/hooks/api/useListOfSpecificUsers.ts
  src/hooks/api/useMessageCreateMutation.ts
  src/hooks/api/useMessageSeen.ts
  src/hooks/api/useNotificationSeen.ts
  src/hooks/api/usePostCommentCreateMutation.ts
  src/hooks/api/usePostCreateMutation.ts
  src/hooks/api/usePostDeleteMutation.ts
  src/hooks/api/usePostUpdateMutation.ts
  src/hooks/api/useSignOut.ts
  src/hooks/api/useUser.ts
  src/pages/Channel/index.tsx
  src/pages/Message/index.tsx
  src/pages/MessageListPage/index.tsx
  src/pages/PostCreate/index.tsx
  src/route/AppRouter.tsx
  src/utils/parse.ts
Labels: 🛠️refactor

#129 📎 chore: 불필요한 패키지, 파일 삭제
  .eslintrc.cjs
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  api/index.ts
  package-lock.json
  package.json
  public/vite.svg
  src/components/Channel/ChannelPosts/index.tsx
  src/components/Common/Modal/index.stories.tsx
  src/hooks/api/useConfirmAuthQuery.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: 📎 chore

#133 📎chore: 최익 task 빌드 오류 해결 및 메시지 리스트의 쌓인 메시지 개수 버그 수정
  src/components/MessageList/SearchBar/index.tsx
  src/components/MessageList/UserList/index.tsx
  src/components/PostComment/PrePost/index.tsx
  src/hooks/api/useListOfSpecificUsers.ts
  src/pages/MessageListPage/index.tsx
Labels: 📎 chore

#137 📎 chore: 서비스 소개 추가
  src/components/Common/Button/index.tsx
  src/components/Common/Responsive/ServiceInformation/index.style.tsx
  src/components/Common/Responsive/ServiceInformation/index.tsx
  src/components/Common/Responsive/index.tsx
Labels: 📎 chore

#138 Refactor/#134/choi task bug modify
  src/App.tsx
  src/api/post.ts
  src/components/Message/DM/index.style.tsx
  src/components/Message/DM/index.tsx
  src/components/Message/SendMessage/index.style.tsx
  src/components/MessageList/UserList/index.style.tsx
  src/components/MessageList/UserList/index.tsx
  src/components/Post/Footer/index.style.tsx
  src/components/Post/Footer/index.tsx
  src/components/Post/Header/index.style.tsx
  src/components/Post/Letter/index.style.tsx
  src/components/Post/Letter/index.tsx
  src/components/Post/Warning/index.style.tsx
  src/components/Post/index.style.tsx
  src/components/Post/index.tsx
  src/components/PostComment/Comment/index.style.tsx
  src/components/PostComment/Footer/index.style.tsx
  src/components/PostComment/Footer/index.tsx
  src/components/PostComment/Header/index.style.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.style.tsx
  src/components/PostComment/index.tsx
  src/hooks/api/useGetPostDetailQuery.ts
  src/hooks/api/useMessageSeen.ts
  src/hooks/api/usePostUpdateMutation.ts
  src/hooks/api/useSignIn.ts
  src/hooks/api/useSignOut.ts
  src/hooks/api/useUserList.ts
  src/pages/Message/index.style.tsx
  src/pages/Message/index.tsx
  src/pages/MessageListPage/index.tsx
Labels: 🐛 fix, 🛠️refactor

#140 💄 design: 404 페이지 버튼 사이즈 수정
  src/components/Post/Letter/index.tsx
  src/pages/NotFoundPage/index.tsx
Labels: 💄 design

#141 🔨refactor: channel, notification 기능 개선
  public/assets/images/background/gradation.png
  public/assets/images/background/mountain.png
  public/assets/images/background/mountain2.png
  public/assets/images/background/mountain3.png
  public/assets/images/background/original.png
  public/assets/images/background/paper.png
  public/assets/images/background/paper2.png
  public/assets/images/background/per.png
  public/assets/images/background/see.png
  src/App.tsx
  src/assets/Alarm.svg
  src/components/Account/SignInBtn/index.tsx
  src/components/Alarm/AlarmItem/index.tsx
  src/components/Alarm/AlarmItem/type.ts
  src/components/Channel/ChannelButton/index.tsx
  src/components/Channel/ChannelPosts/index.tsx
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/components/ChannelTemplate/SelectBackground/index.tsx
  src/components/Common/HamburgerMenu/index.tsx
  src/components/Common/Modal/index.style.tsx
  src/components/Common/NotificationMenu/index.style.tsx
  src/components/Common/NotificationMenu/index.tsx
  src/components/Common/SearchBar/index.style.tsx
  src/components/Common/SearchBar/index.tsx
  src/components/DarkMode/index.tsx
  src/hooks/useTheme.tsx
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.style.tsx
  src/pages/ChannelList/index.tsx
  src/pages/ChannelTemplate/index.tsx
  src/pages/PostCreate/index.tsx
  src/pages/ReceivedPostListPage/index.style.tsx
  src/pages/ReceivedPostListPage/index.tsx
  src/route/AppRouter.tsx
  src/route/MenuBar/index.style.tsx
  src/route/MenuBar/index.tsx
  src/utils/anonymous.ts
  src/utils/parse.ts
Labels: 🛠️refactor

#143 🔨refactor: 정렬 및 클릭 오류 수정
  src/components/Channel/ChannelAnimation/index.style.tsx
  src/components/Channel/ChannelOption/index.style.tsx
  src/components/Channel/ChannelOption/index.tsx
  src/components/MessageList/Header/index.style.tsx
  src/components/Post/Header/index.style.tsx
  src/components/PostComment/Header/index.style.tsx
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.style.tsx
  src/pages/ChannelList/index.tsx
  src/utils/parse.ts
Labels: 🐛 fix, 💄 design

#145 🔨refactor: 마이페이지 및 유저페이지 수정
  package-lock.json
  src/App.tsx
  src/components/Channel/ChannelPosts/index.tsx
  src/components/Common/EmptyChannel/index.style.tsx
  src/components/Common/EmptyChannel/index.tsx
  src/components/Common/HamburgerMenu/index.tsx
  src/components/Common/NotificationMenu/index.tsx
  src/components/Common/ProfileImg/index.tsx
  src/components/MessageList/UserList/index.tsx
  src/components/Mypage/FollowListItem/index.tsx
  src/components/Mypage/Header/index.style.tsx
  src/components/Mypage/Header/index.tsx
  src/components/Mypage/MypageLayout/index.style.tsx
  src/components/Mypage/PostList/index.tsx
  src/components/Mypage/Sidebar/index.tsx
  src/components/PostComment/PrePost/index.tsx
  src/hooks/api/useAuthorPost.ts
  src/hooks/api/useCreateFollow.ts
  src/hooks/api/useDeleteFollow.ts
  src/hooks/api/useUserLikeList.ts
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.tsx
  src/pages/ReceivedPostListPage/index.tsx
  src/pages/UserPage/index.style.tsx
  src/pages/UserPage/index.tsx
  src/route/AppRouter.tsx
  src/types/ResponseType.tsx
Labels: 🛠️refactor

#146 💄style: post, comment 페이지 UI 수정
  src/components/Post/Letter/index.style.tsx
  src/components/Post/Letter/index.tsx
  src/components/Post/index.tsx
  src/components/PostComment/Comment/index.style.tsx
  src/components/PostComment/Comment/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.tsx
Labels: 💄 design

#149 🔨 refactor: axiosInstance 타입 수정, 모듈 분리
  src/api/HTTPError.ts
  src/api/axiosInstance.ts
  src/api/axiosInstance/HTTPError.ts
  src/api/axiosInstance/index.ts
  src/api/axiosInstance/interceptors.ts
  src/api/index.d.ts
  src/api/member.ts
  src/components/PostComment/index.tsx
  src/constants/api.ts
  src/hooks/api/useSignIn.ts
  src/hooks/api/useSignOut.ts
  src/hooks/api/useSignUp.ts
  src/hooks/api/useUserInfomationQuery.ts
Labels: 🛠️refactor

#151 ✨feat: 회원별 채널 안내 구현
  src/components/Alarm/AlarmItem/index.tsx
  src/components/Alarm/AlarmItem/type.ts
  src/components/Alarm/AlarmList/index.tsx
  src/components/Channel/ChannelButton/index.tsx
  src/components/Channel/ChannelOpen/index.tsx
  src/components/Channel/ChannelPosts/index.tsx
  src/components/Common/NotificationMenu/index.tsx
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.style.tsx
  src/pages/ChannelList/index.tsx
  src/pages/PostCreate/index.style.tsx
  src/pages/PostCreate/index.tsx
  src/utils/access.ts
  src/utils/anonymous.ts
Labels: ✨feat

#152 🐛 fix: 동적 이미지 연결 및 권한별 알림 설정
  public/assets/letter/blue.png
  public/assets/letter/green.png
  public/assets/letter/mint.png
  public/assets/letter/orange.png
  public/assets/letter/pink.png
  public/assets/letter/purple.png
  public/assets/letter/red.png
  public/assets/letter/white.png
  public/assets/letter/yellow.png
  src/components/Channel/ChannelButton/index.tsx
  src/components/Channel/ChannelPosts/index.tsx
  src/components/Common/Responsive/index.tsx
  src/pages/Channel/index.tsx
  src/pages/ChannelList/index.tsx
  src/pages/PostCreate/index.tsx
  src/utils/parse.ts
Labels: 🐛 fix

#153 📎 chore: 불필요한 코드 제거
  src/components/Common/NotificationMenu/index.tsx
Labels: 📎 chore

#154 🔨 refactor: 익명 사용자 접근 수정
  src/components/Common/HamburgerMenu/index.tsx
  src/components/Common/SignIn/index.tsx
  src/hooks/useIsLoggedIn.tsx
  src/route/AuthMiddleware.tsx
Labels: 🛠️refactor

#155 🐛fix: post, comment
  src/components/Message/DM/index.style.tsx
  src/components/Message/DM/index.tsx
  src/components/Message/Header/index.tsx
  src/components/MessageList/Header/index.style.tsx
  src/components/MessageList/Header/index.tsx
  src/components/MessageList/SearchBar/index.style.tsx
  src/components/MessageList/SearchBar/index.tsx
  src/components/MessageList/UserList/index.style.tsx
  src/components/MessageList/UserList/index.tsx
  src/components/Post/Letter/index.style.tsx
  src/components/Post/Letter/index.tsx
  src/components/Post/index.style.tsx
  src/components/Post/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.tsx
  src/hooks/api/useSignIn.ts
  src/hooks/api/useSignOut.ts
  src/hooks/api/useUserOnline.ts
  src/pages/Message/index.tsx
  src/pages/MessageListPage/index.tsx
Labels: 🐛 fix, 💄 design

#156 🐛 fix: 동적 이미지 연결 수정
  src/components/Channel/ChannelButton/index.tsx
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/components/ChannelTemplate/SelectBackground/index.tsx
Labels: 🐛 fix

#159 🐛 fix: 동적 이미지 연결 수정
  src/components/Channel/ChannelOption/index.tsx
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/hooks/api/useGetChannelInfo.ts
  src/pages/Channel/index.tsx
  src/utils/parse.ts
Labels: 🐛 fix

#161 🐛 fix: 익명 사용자 여부 체크 로직 수정
  src/hooks/api/useSignIn.ts
  src/hooks/api/useSignOut.ts
  src/hooks/useIsLoggedIn.tsx
  src/route/MenuBar/index.tsx
  src/store/auth.ts
Labels: 🐛 fix

#167 🔨refactor: 비회원이 post 페이지 접근 시, 비회원 토큰을 발급 받을 수 있도록 로그인 페이지로 이동
  src/components/Post/Footer/index.tsx
  src/components/Post/index.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.tsx
  src/pages/MessageListPage/index.tsx
Labels: 🛠️refactor

#173 Fix/#168/post page warning message modefiy
  src/components/ChannelTemplate/SelectBackground/index.style.tsx
  src/components/Message/SendMessage/index.tsx
  src/components/Post/Warning/index.tsx
  src/components/Post/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.tsx
  src/pages/Channel/index.tsx
Labels: 🐛 fix, 💄 design

#175 🐛 fix: 라우팅 수정
  src/hooks/useIsLoggedIn.tsx
  src/route/AuthMiddleware.tsx
Labels: 🐛 fix

#179 🐛fix: 마이페이지 새로고침 및 프로필 업데이트 에러 수정
  src/App.tsx
  src/components/Common/ProfileImg/index.tsx
  src/components/Common/Responsive/ServiceInformation/index.tsx
  src/components/MessageList/UserList/index.tsx
  src/components/Mypage/MypageLayout/index.tsx
  src/components/Mypage/ProfileUpdate/index.style.tsx
  src/components/Mypage/ProfileUpdate/index.tsx
  src/pages/Mypage/index.tsx
Labels: 🐛 fix

#181 ⚙️ setting: Sentry 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/axiosInstance/interceptors.ts
  src/components/Alarm/AlarmItem/type.ts
  src/main.tsx
Labels: ⚙️ setting

#184 🐛 fix: 라우터 수정
  src/components/Common/SignIn/index.tsx
  src/route/AuthMiddleware.tsx
Labels: 🐛 fix

#185 ✨feat: 댓글 페이지 댓글 및 좋아요 클릭시 알림 전송 기능 추가
  src/components/Post/index.tsx
  src/components/PostComment/Comment/index.style.tsx
  src/components/PostComment/PrePost/index.style.tsx
  src/components/PostComment/PrePost/index.tsx
  src/components/PostComment/index.style.tsx
  src/components/PostComment/index.tsx
  src/hooks/api/useLikeCreateMutation.ts
  src/hooks/api/usePostCommentCreateMutation.ts
Labels: ✨feat

#186 🐛 fix: sentry 빌드 에러 수정
  src/App.tsx
  src/api/axiosInstance/interceptors.ts
  src/main.tsx
Labels: 🐛 fix, ⚙️ setting

#188 💄design: 커서 모양 pointer로 수정
  src/components/Alarm/AlarmItem/index.style.tsx
  src/components/Alarm/AlarmList/index.style.tsx
  src/components/Channel/ChannelClose/index.style.tsx
  src/components/Channel/ChannelPosts/index.style.tsx
  src/components/Common/NotificationMenu/index.style.tsx
  src/components/Common/ProfileImg/index.style.tsx
  src/components/Common/ProfileImg/index.tsx
  src/components/Mypage/FollowListItem/index.tsx
  src/components/Mypage/Sidebar/index.style.tsx
  src/components/Mypage/Sidebar/index.tsx
  src/components/PostComment/PrePost/index.style.tsx
Labels: 💄 design

#190 ✨ feat: google-ga 설정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/utils/RouteChangeTracker.tsx
Labels: ✨feat

#196 ✨feat: 메시지 전송시 shift+enter 입력시 줄바꿈 된 텍스트 서버 전송 기능 추가
  src/components/Message/DM/index.style.tsx
  src/components/Message/SendMessage/index.tsx
Labels: ✨feat

#194 🔨refactor: 메세지 페이지의 컴포넌트 key 누락 및 특정 유저 정보 요청 수정
  src/components/Message/DM/index.tsx
  src/hooks/api/useUser.ts
Labels: 🐛 fix, 🛠️refactor
